// Mock data cho Quản lý hợp đồng
export const contractsData = [
  {
    id: 1,
    contractNumber: 'HD-2024-001',
    contractType: 'Hợp đồng lao động',
    partyA: {
      name: 'Công ty TNHH ABC',
      address: '123 Đường ABC, Quận 1, TP.HCM',
      taxCode: '0123456789',
      representative: 'Nguyễn Văn Admin',
      position: 'Giám đốc',
      phone: '0281234567',
      email: 'contact@abc.com',
    },
    partyB: {
      name: 'Nguyễn Văn A',
      idCard: '001234567890',
      address: '456 Đường XYZ, Quận 2, TP.HCM',
      phone: '0901234567',
      email: 'nguyenvana@example.com',
      position: 'Nhân viên',
    },
    contractDate: '2024-01-15',
    effectiveDate: '2024-01-15',
    expiryDate: '2024-12-31',
    salary: 15000000,
    workingHours: '8 giờ/ngày, 5 ngày/tuần',
    jobDescription: 'Thực hiện các công việc được giao bởi cấp trên',
    terms: [
      'Bên B cam kết thực hiện đầy đủ các công việc được giao',
      'Bên A cam kết trả lương đúng hạn',
      'Hai bên tuân thủ các quy định của pháp luật',
    ],
    status: 'active',
    notes: 'Hợp đồng lao động 1 năm',
  },
  {
    id: 2,
    contractNumber: 'HD-2024-002',
    contractType: 'Hợp đồng dịch vụ',
    partyA: {
      name: 'Công ty TNHH ABC',
      address: '123 Đường ABC, Quận 1, TP.HCM',
      taxCode: '0123456789',
      representative: 'Nguyễn Văn Admin',
      position: 'Giám đốc',
      phone: '0281234567',
      email: 'contact@abc.com',
    },
    partyB: {
      name: 'Công ty Cổ phần XYZ',
      taxCode: '0123456790',
      address: '789 Đường DEF, Quận 3, TP.HCM',
      representative: 'Trần Thị B',
      position: 'Giám đốc',
      phone: '0282345678',
      email: 'info@xyz.com',
    },
    contractDate: '2024-02-01',
    effectiveDate: '2024-02-01',
    expiryDate: '2024-12-31',
    serviceDescription: 'Cung cấp dịch vụ tư vấn công nghệ thông tin',
    serviceFee: 50000000,
    paymentTerms: 'Thanh toán 50% khi ký hợp đồng, 50% khi hoàn thành',
    terms: [
      'Bên B cung cấp dịch vụ đúng chất lượng và thời hạn',
      'Bên A thanh toán đúng hạn theo thỏa thuận',
      'Hai bên bảo mật thông tin của nhau',
    ],
    status: 'active',
    notes: 'Hợp đồng dịch vụ 11 tháng',
  },
  {
    id: 3,
    contractNumber: 'HD-2024-003',
    contractType: 'Hợp đồng mua bán',
    partyA: {
      name: 'Công ty TNHH ABC',
      address: '123 Đường ABC, Quận 1, TP.HCM',
      taxCode: '0123456789',
      representative: 'Nguyễn Văn Admin',
      position: 'Giám đốc',
      phone: '0281234567',
      email: 'contact@abc.com',
    },
    partyB: {
      name: 'Công ty TNHH DEF',
      taxCode: '0123456791',
      address: '321 Đường GHI, Quận 4, TP.HCM',
      representative: 'Lê Văn C',
      position: 'Giám đốc',
      phone: '0283456789',
      email: 'hello@def.com',
    },
    contractDate: '2024-03-10',
    effectiveDate: '2024-03-10',
    expiryDate: '2024-06-10',
    productDescription: 'Mua bán thiết bị văn phòng',
    totalAmount: 100000000,
    paymentTerms: 'Thanh toán 100% khi giao hàng',
    deliveryTerms: 'Giao hàng trong vòng 7 ngày',
    terms: [
      'Bên B giao hàng đúng số lượng và chất lượng',
      'Bên A thanh toán đúng hạn',
      'Bảo hành sản phẩm 12 tháng',
    ],
    status: 'active',
    notes: 'Hợp đồng mua bán 3 tháng',
  },
];

