export const costsData = [
  {
    id: 1,
    requester: 'Nguyễn Văn A',
    department: 'Kinh doanh',
    requestDate: '2023-01-15',
    projectCode: 'TACs25ND80',
    transactionType: 'Chi',
    transactionObject: 'Nhà hàng Biển Đông',
    content: 'Chi phí tiếp khách',
    description: 'Tiếp khách dự án TACs25ND80',
    amountBeforeTax: 5000000,
    taxRate: '10%',
    totalAmount: 5500000,
    paymentMethod: 'Chuyển khoản',
    bank: 'Vietcombank',
    accountNumber: '0011001234567',
    voucherType: 'Hóa đơn',
    voucherNumber: 'HD001234',
    voucherDate: '2023-01-15',
    attachment: 'hoadon_tiepkhach.pdf',
    paymentStatus: 'Đã thanh toán',
    rejectionReason: '',
    note: 'Đã duyệt bởi Giám đốc',
  },
  {
    id: 2,
    requester: 'Trần Thị B',
    department: 'Hành chính',
    requestDate: '2023-01-20',
    projectCode: '',
    transactionType: 'Chi',
    transactionObject: 'Công ty VPP Hồng Hà',
    content: 'Mua văn phòng phẩm',
    description: 'Mua giấy, bút cho văn phòng',
    amountBeforeTax: 2000000,
    taxRate: '8%',
    totalAmount: 2160000,
    paymentMethod: 'Tiền mặt',
    bank: '',
    accountNumber: '',
    voucherType: 'Hóa đơn',
    voucherNumber: 'HD005678',
    voucherDate: '2023-01-20',
    attachment: 'hoadon_vpp.pdf',
    paymentStatus: 'Đã thanh toán',
    rejectionReason: '',
    note: '',
  },
  {
    id: 3,
    requester: 'Lê Văn C',
    department: 'Kỹ thuật',
    requestDate: '2023-02-01',
    projectCode: 'STCHue25ND80',
    transactionType: 'Tạm ứng',
    transactionObject: 'Lê Văn C',
    content: 'Tạm ứng công tác phí',
    description: 'Đi công tác Huế triển khai dự án',
    amountBeforeTax: 3000000,
    taxRate: 'No VAT',
    totalAmount: 3000000,
    paymentMethod: 'Chuyển khoản',
    bank: 'Techcombank',
    accountNumber: '1903456789012',
    voucherType: 'Phiếu chi',
    voucherNumber: 'PC001',
    voucherDate: '2023-02-01',
    attachment: 'de_nghi_tam_ung.pdf',
    paymentStatus: 'Đợi duyệt',
    rejectionReason: '',
    note: '',
  },
  {
    id: 4,
    requester: 'Phạm Thị D',
    department: 'Kế toán',
    requestDate: '2023-02-05',
    projectCode: '',
    transactionType: 'Thu',
    transactionObject: 'Khách hàng XYZ',
    content: 'Thu tiền hợp đồng đợt 1',
    description: 'Khách hàng thanh toán 50% giá trị hợp đồng',
    amountBeforeTax: 50000000,
    taxRate: '10%',
    totalAmount: 55000000,
    paymentMethod: 'Chuyển khoản',
    bank: 'Vietinbank',
    accountNumber: '111222333',
    voucherType: 'Phiếu thu',
    voucherNumber: 'PT001',
    voucherDate: '2023-02-05',
    attachment: 'unc_khachhang.pdf',
    paymentStatus: 'Đã thanh toán',
    rejectionReason: '',
    note: '',
  },
  {
    id: 5,
    requester: 'Hoàng Văn E',
    department: 'Marketing',
    requestDate: '2023-02-10',
    projectCode: 'SCTQTri25ND80',
    transactionType: 'Hoàn ứng',
    transactionObject: 'Hoàng Văn E',
    content: 'Hoàn ứng chi phí chạy quảng cáo',
    description: 'Chi phí chạy quảng cáo Facebook tháng 1',
    amountBeforeTax: 1500000,
    taxRate: 'No VAT',
    totalAmount: 1500000,
    paymentMethod: 'Tiền mặt',
    bank: '',
    accountNumber: '',
    voucherType: 'Phiếu thu',
    voucherNumber: 'PT002',
    voucherDate: '2023-02-10',
    attachment: 'bang_ke_chi_phi.xlsx',
    paymentStatus: 'Quản lý duyệt',
    rejectionReason: '',
    note: '',
  },
];
