// Mock data cho Quản lý khách hàng
const baseCustomers = [
  {
    id: 1,
    name: 'Nguyễn Văn A',
    email: 'nguyenvana@example.com',
    phone: '0901234567',
    address: '123 Đường ABC, Quận 1, TP.HCM',
    company: 'Công ty ABC',
    taxCode: '0101234567',
    representativeName: 'Nguyễn Văn A',
    representativePosition: 'Giám đốc',
    representativePhone: '0901234567',
    businessNeeds: 'Cần tư vấn giải pháp quản lý kho',
    businessScale: '50-100 nhân sự',
    businessIndustry: 'Sản xuất',
    copyrightStatus: 'Đã đăng ký',
    trademarkStatus: 'Đã bảo hộ',
    patentStatus: 'Không có',
    industrialDesign: 'Đang thẩm định',
    contractStatus: 'Đang thực hiện',
    status: 'active',
    totalOrders: 15,
    totalRevenue: 50000000,
    joinDate: '2023-01-15',
    notes: 'Khách hàng VIP',
    productsServices: 'Phần mềm quản lý',
    ipGroup: 'Nhóm 1',
    consultingStatus: 'Đã tư vấn',
    filingStatus: 'Đã viết hồ sơ',
    documentLink: 'https://drive.google.com/drive/u/0/folders/1',
    authorization: 'Đã có',
    applicationReviewStatus: 'Đang xét duyệt',
    priority: 'Mức 1',
    contractPaid: '50%',
    contractValue: 100000000,
    startDate: '2023-01-20',
    endDate: '2023-12-20',
    implementationDays: 330,
    potentialLevel: 'Cao',
    sourceClassification: 'Đối tác',
    nsnnSource: '',
  },
  {
    id: 2,
    name: 'Trần Thị B',
    email: 'tranthib@example.com',
    phone: '0902345678',
    address: '456 Đường XYZ, Quận 2, TP.HCM',
    company: 'Công ty XYZ',
    taxCode: '0102345678',
    representativeName: 'Trần Thị B',
    representativePosition: 'Trưởng phòng mua hàng',
    representativePhone: '0902345678',
    businessNeeds: 'Tìm kiếm nguồn nguyên liệu mới',
    businessScale: '10-50 nhân sự',
    businessIndustry: 'Thương mại',
    copyrightStatus: 'Chưa có',
    trademarkStatus: 'Đang đăng ký',
    patentStatus: 'Không có',
    industrialDesign: 'Không có',
    contractStatus: 'Sắp hết hạn',
    status: 'active',
    totalOrders: 8,
    totalRevenue: 25000000,
    joinDate: '2023-03-20',
    notes: '',
    productsServices: 'Thực phẩm sạch',
    ipGroup: 'Nhóm 2',
    consultingStatus: 'Đang tư vấn',
    filingStatus: 'Chưa triển khai',
    documentLink: '',
    authorization: 'Chưa có',
    applicationReviewStatus: 'Chưa có',
    priority: 'Mức 2',
    contractPaid: '0%',
    contractValue: 50000000,
    startDate: '2023-04-01',
    endDate: '2023-10-01',
    implementationDays: 180,
    potentialLevel: 'Trung bình',
    sourceClassification: 'Vãng lai',
    nsnnSource: '',
  },
  {
    id: 3,
    name: 'Lê Văn C',
    email: 'levanc@example.com',
    phone: '0903456789',
    address: '789 Đường DEF, Quận 3, TP.HCM',
    company: 'Công ty DEF',
    taxCode: '0103456789',
    representativeName: 'Lê Văn C',
    representativePosition: 'Phó Giám đốc',
    representativePhone: '0903456789',
    businessNeeds: 'Mở rộng thị trường miền Bắc',
    businessScale: '100-200 nhân sự',
    businessIndustry: 'Xây dựng',
    copyrightStatus: 'Đã đăng ký',
    trademarkStatus: 'Đã bảo hộ',
    patentStatus: 'Đã có bằng',
    industrialDesign: 'Đã bảo hộ',
    contractStatus: 'Đã thanh lý',
    status: 'inactive',
    totalOrders: 3,
    totalRevenue: 8000000,
    joinDate: '2022-11-10',
    notes: 'Khách hàng cũ',
    productsServices: 'Vật liệu xây dựng',
    ipGroup: 'Nhóm 3',
    consultingStatus: 'Đã tư vấn',
    filingStatus: 'Đã viết hồ sơ',
    documentLink: 'https://drive.google.com/drive/u/0/folders/3',
    authorization: 'Đã có',
    applicationReviewStatus: 'Được duyệt',
    priority: 'Mức 3',
    contractPaid: '100%',
    contractValue: 200000000,
    startDate: '2022-12-01',
    endDate: '2023-06-01',
    implementationDays: 180,
    potentialLevel: 'Thấp',
    sourceClassification: 'NSNN',
    nsnnSource: 'Sở TC Huế',
  },
  {
    id: 4,
    name: 'Phạm Thị D',
    email: 'phamthid@example.com',
    phone: '0904567890',
    address: '321 Đường GHI, Quận 4, TP.HCM',
    company: 'Công ty GHI',
    taxCode: '0104567890',
    representativeName: 'Phạm Thị D',
    representativePosition: 'Kế toán trưởng',
    representativePhone: '0904567890',
    businessNeeds: 'Nâng cấp hệ thống phần mềm kế toán',
    businessScale: '20-30 nhân sự',
    businessIndustry: 'Dịch vụ',
    copyrightStatus: 'Không áp dụng',
    trademarkStatus: 'Chưa đăng ký',
    patentStatus: 'Không có',
    industrialDesign: 'Không có',
    contractStatus: 'Đang đàm phán gia hạn',
    status: 'active',
    totalOrders: 12,
    totalRevenue: 40000000,
    joinDate: '2023-02-05',
    notes: '',
    productsServices: 'Dịch vụ kế toán',
    ipGroup: 'Nhóm 4',
    consultingStatus: 'Chưa tư vấn',
    filingStatus: 'Chưa triển khai',
    documentLink: '',
    authorization: 'Chưa có',
    applicationReviewStatus: 'Chưa có',
    priority: 'Mức 2',
    contractPaid: '0%',
    contractValue: 30000000,
    startDate: '',
    endDate: '',
    implementationDays: 0,
    potentialLevel: 'Trung bình',
    sourceClassification: 'Sự kiện',
    nsnnSource: '',
  },
  {
    id: 5,
    name: 'Hoàng Văn E',
    email: 'hoangvane@example.com',
    phone: '0905678901',
    address: '654 Đường JKL, Quận 5, TP.HCM',
    company: 'Công ty JKL',
    taxCode: '0105678901',
    representativeName: 'Hoàng Văn E',
    representativePosition: 'Giám đốc điều hành',
    representativePhone: '0905678901',
    businessNeeds: 'Tư vấn tái cấu trúc doanh nghiệp',
    businessScale: '500+ nhân sự',
    businessIndustry: 'Công nghệ',
    copyrightStatus: 'Đã đăng ký nhiều bản quyền',
    trademarkStatus: 'Thương hiệu mạnh',
    patentStatus: 'Sở hữu 5 bằng sáng chế',
    industrialDesign: 'Đã đăng ký',
    contractStatus: 'Hợp đồng dài hạn',
    status: 'active',
    totalOrders: 20,
    totalRevenue: 75000000,
    joinDate: '2022-09-15',
    notes: 'Khách hàng thân thiết',
    productsServices: 'Giải pháp AI',
    ipGroup: 'Nhóm 1',
    consultingStatus: 'Đã tư vấn',
    filingStatus: 'Đang viết hồ sơ',
    documentLink: 'https://drive.google.com/drive/u/0/folders/5',
    authorization: 'Đã có',
    applicationReviewStatus: 'Có OA chưa phản hồi',
    priority: 'Mức 1',
    contractPaid: '80%',
    contractValue: 500000000,
    startDate: '2022-10-01',
    endDate: '2024-10-01',
    implementationDays: 730,
    potentialLevel: 'Cao',
    sourceClassification: 'Đối tác',
    nsnnSource: '',
  },
  {
    id: 6,
    name: 'Vũ Thị F',
    email: 'vuthif@example.com',
    phone: '0906789012',
    address: '987 Đường MNO, Quận 6, TP.HCM',
    company: 'Công ty MNO',
    taxCode: '0106789012',
    representativeName: 'Vũ Thị F',
    representativePosition: 'Trưởng phòng Marketing',
    representativePhone: '0906789012',
    businessNeeds: 'Chiến dịch marketing mới',
    businessScale: '50-100 nhân sự',
    businessIndustry: 'Bán lẻ',
    copyrightStatus: 'Đang xử lý',
    trademarkStatus: 'Đã nộp đơn',
    patentStatus: 'Không có',
    industrialDesign: 'Không có',
    contractStatus: 'Đang thực hiện',
    status: 'active',
    totalOrders: 6,
    totalRevenue: 18000000,
    joinDate: '2023-04-12',
    notes: '',
    productsServices: 'Thời trang',
    ipGroup: 'Nhóm 2',
    consultingStatus: 'Đang tư vấn',
    filingStatus: 'Đang viết hồ sơ',
    documentLink: '',
    authorization: 'Đã có',
    applicationReviewStatus: 'Đang xét duyệt',
    priority: 'Mức 2',
    contractPaid: '30%',
    contractValue: 60000000,
    startDate: '2023-05-01',
    endDate: '2023-11-01',
    implementationDays: 180,
    potentialLevel: 'Trung bình',
    sourceClassification: 'Vãng lai',
    nsnnSource: '',
  },
];

export const customersData = [
  ...baseCustomers,
  ...Array.from({ length: 100 }, (_, i) => {
    const id = baseCustomers.length + i + 1;
    const scales = ['Siêu nhỏ', 'Nhỏ', 'Vừa'];
    const industries = ['Thương mại', 'Dịch vụ', 'Sản xuất', 'Công nghệ', 'Xây dựng'];
    const statuses = ['active', 'inactive'];
    const orders = (i % 25) + 1;
    const revenue = ((i % 60) + 5) * 1000000;
    const month = ((i % 12) + 1).toString().padStart(2, '0');
    const day = ((i % 28) + 1).toString().padStart(2, '0');
    const phoneSuffix = (100000 + i).toString().slice(0, 7);
    const taxSuffix = (1000000 + i).toString().slice(0, 7);
    return {
      id,
      name: `Khách hàng Auto ${id}`,
      email: `customer${id}@example.com`,
      phone: `090${phoneSuffix}`,
      address: `Số ${id}, Đường Auto, Quận ${((i % 10) + 1)}`,
      company: `Công ty Auto ${id}`,
      taxCode: `010${taxSuffix}`,
      representativeName: `Đại diện ${id}`,
      representativePosition: 'Giám đốc',
      representativePhone: `090${phoneSuffix}`,
      businessNeeds: 'Tư vấn giải pháp',
      businessScale: scales[i % scales.length],
      businessIndustry: industries[i % industries.length],
      copyrightStatus: 'Đang xử lý',
      trademarkStatus: 'Đang đăng ký',
      patentStatus: 'Không có',
      industrialDesign: 'Không có',
      contractStatus: 'Đang thực hiện',
      status: statuses[i % statuses.length],
      totalOrders: orders,
      totalRevenue: revenue,
      joinDate: `2023-${month}-${day}`,
      notes: '',
      productsServices: 'Dịch vụ',
      ipGroup: `Nhóm ${((i % 4) + 1)}`,
      consultingStatus: 'Đang tư vấn',
      filingStatus: 'Chưa triển khai',
      documentLink: '',
      authorization: 'Chưa có',
      applicationReviewStatus: 'Chưa có',
      priority: `Mức ${((i % 3) + 1)}`,
      contractPaid: `${(i % 5) * 20}%`,
      contractValue: revenue * 2,
      startDate: `2023-${month}-01`,
      endDate: `2023-${month}-28`,
      implementationDays: ((i % 12) + 1) * 10,
      potentialLevel: ['Thấp', 'Trung bình', 'Cao'][i % 3],
      sourceClassification: ['Vãng lai', 'Đối tác', 'Sự kiện', 'NSNN'][i % 4],
      nsnnSource: i % 4 === 3 ? `Sở TC ${((i % 5) + 1)}` : '',
    };
  }),
];
