export const roles = [
  { key: 'marketing_sales', label: 'Marketing/ Sales' },
  { key: 'ip_executive', label: 'IP Executive' },
  { key: 'ip_manager', label: 'IP Manager' },
  { key: 'director', label: 'Giám đốc' },
  { key: 'ceo', label: 'Tổng giám đốc' },
  { key: 'accountant', label: 'Kế toán' },
  { key: 'admin', label: 'Admin' },
];

export const schedulingFields = [
  {
    key: 'group_actions',
    label: 'I. Thao tác',
    children: [
      { key: 'seedData', label: 'Dữ liệu mẫu' },
      { key: 'generate', label: 'Tạo lịch' },
      { key: 'export', label: 'Xuất Excel' },
    ],
  },
  {
    key: 'group_config',
    label: 'II. Cấu hình',
    children: [
      { key: 'config', label: 'Form cấu hình' },
    ],
  },
  {
    key: 'group_view',
    label: 'III. Hiển thị',
    children: [
      { key: 'view', label: 'Xem lịch' },
    ],
  },
];

export const qlkhFields = [
  {
    key: 'group_general',
    label: 'I. Nhóm thông tin chung',
    children: [
      { key: 'name', label: 'Doanh nghiệp' },
      { key: 'businessScale', label: 'Quy mô DN' },
      { key: 'taxCode', label: 'Mã số thuế' },
      { key: 'address', label: 'Địa chỉ' },
      { key: 'representativeName', label: 'Người đại diện' },
      { key: 'representativePosition', label: 'Chức vụ' },
      { key: 'idNumber', label: 'CCCD/Hộ chiếu' },
      { key: 'phone', label: 'SĐT DN' },
      { key: 'email', label: 'Email DN' },
      { key: 'contactPerson', label: 'Người liên hệ' },
      { key: 'contactPhone', label: 'SĐT người liên hệ' },
      { key: 'contactEmail', label: 'Email người liên hệ' },
    ],
  },
  {
    key: 'group_need',
    label: 'II. Nhu cầu - Lead - Tiềm năng',
    children: [
      { key: 'businessNeeds', label: 'Nhu cầu DN' },
      { key: 'potentialLevel', label: 'Mức độ tiềm năng' },
      { key: 'priority', label: 'Ưu tiên' },
      { key: 'sourceClassification', label: 'Phân loại nguồn' },
      { key: 'nsnnSource', label: 'Nguồn NSNN' },
    ],
  },
  {
    key: 'group_core_ip',
    label: 'III. Thông tin SHTT cốt lõi',
    children: [
      { key: 'brandName', label: 'Thương hiệu' },
      { key: 'productsServices', label: 'Sản phẩm/DV' },
      { key: 'ipGroup', label: 'Nhóm SHTT' },
      { key: 'owner', label: 'Chủ sở hữu' },
      { key: 'protectionTerritory', label: 'Lãnh thổ bảo hộ' },
      { key: 'authorization', label: 'Uỷ quyền' },
    ],
  },
  {
    key: 'group_legal',
    label: 'IV. Hồ sơ đơn – văn bằng – pháp lý',
    children: [
      { key: 'filingStatus', label: 'Tình trạng nộp đơn' },
      { key: 'filingDate', label: 'Ngày nộp đơn' },
      { key: 'applicationCode', label: 'Mã đơn/Công bố/VB' },
      { key: 'issueDate', label: 'Ngày cấp' },
      { key: 'expiryDate', label: 'Ngày hết hạn' },
      { key: 'applicationReviewStatus', label: 'Tình trạng xét duyệt' },
      { key: 'processingDeadline', label: 'Hạn xử lý' },
    ],
  },
  {
    key: 'group_renewal',
    label: 'V. Gia hạn & nhắc việc',
    children: [
      { key: 'renewalCycle', label: 'Chu kỳ gia hạn' },
      { key: 'renewalDate', label: 'Ngày cần gia hạn' },
      { key: 'reminderDate', label: 'Ngày nhắc (trước 3 tháng)' },
      { key: 'reminderStatus', label: 'Trạng thái nhắc' },
    ],
  },
  {
    key: 'group_contract',
    label: 'VI. Hợp đồng – tài chính',
    children: [
      { key: 'consultingStatus', label: 'Tình trạng tư vấn' },
      { key: 'contractStatus', label: 'Tình trạng hợp đồng' },
      { key: 'contractNumber', label: 'Số hợp đồng' },
      { key: 'contractValue', label: 'Giá trị hợp đồng' },
      { key: 'stateFee', label: 'Lệ phí NN' },
      { key: 'additionalFee', label: 'Phí phát sinh' },
    ],
  },
  {
    key: 'group_system',
    label: 'VII. Hệ thống – kiểm soát',
    children: [
      { key: 'createdBy', label: 'Người tạo' },
      { key: 'updatedBy', label: 'Người cập nhật' },
      { key: 'updatedAt', label: 'Ngày cập nhật' },
      { key: 'documentLink', label: 'Link hồ sơ giấy tờ' },
    ],
  },
];

export const qlcpFields = [
  {
    key: 'group_request',
    label: 'I. Nhóm thông tin đề nghị – hành chính',
    children: [
      { key: 'requester', label: 'Người đề nghị' },
      { key: 'department', label: 'Phòng ban' },
      { key: 'priority', label: 'Ưu tiên' },
      { key: 'requestDate', label: 'Ngày phát sinh giao dịch' },
      { key: 'projectCode', label: 'Mã dự án' },
    ],
  },
  {
    key: 'group_content',
    label: 'II. Nhóm nội dung chi phí',
    children: [
      { key: 'content', label: 'Nội dung' },
      { key: 'description', label: 'Diễn giải' },
      { key: 'transactionType', label: 'Loại giao dịch' },
      { key: 'voucherType', label: 'Loại chứng từ' },
      { key: 'transactionObject', label: 'Đối tượng Thu/Chi' },
      { key: 'note', label: 'Ghi chú' },
    ],
  },
  {
    key: 'group_finance',
    label: 'III. Nhóm tiền – thuế',
    children: [
      { key: 'amountBeforeTax', label: 'Số tiền (Chưa thuế)' },
      { key: 'taxRate', label: 'Thuế suất' },
      { key: 'totalAmount', label: 'Tổng tiền' },
      { key: 'taxCode', label: 'Mã số thuế' },
    ],
  },
  {
    key: 'group_voucher',
    label: 'IV. Nhóm hóa đơn – chứng từ',
    children: [
      { key: 'voucherNumber', label: 'Số hóa đơn / Chứng từ / Hợp đồng' },
      { key: 'voucherDate', label: 'Ngày hóa đơn / Chứng từ / Hợp đồng' },
      { key: 'attachment', label: 'File đính kèm' },
    ],
  },
  {
    key: 'group_payment',
    label: 'V. Nhóm thanh toán',
    children: [
      { key: 'paymentMethod', label: 'Phương thức thanh toán' },
      { key: 'accountNumber', label: 'Tài khoản' },
      { key: 'bank', label: 'Ngân hàng' },
      { key: 'paymentStatus', label: 'Trạng thái thanh toán' },
    ],
  },
  {
    key: 'group_control',
    label: 'VI. Nhóm phê duyệt – kiểm soát',
    children: [
      { key: 'managerApproval', label: 'Quản lý duyệt' },
      { key: 'directorApproval', label: 'Giám đốc duyệt' },
      { key: 'accountantReview', label: 'Kế toán review' },
      { key: 'adjustReason', label: 'Lý do điều chỉnh' },
      { key: 'rejectionReason', label: 'Lý do từ chối' },
      { key: 'riskFlag', label: 'Cờ kiểm soát rủi ro' },
    ],
  },
];

// Initial permissions (mock)
// R: Read, W: Write, A: Approve, N: None/Hide
export const initialPermissions = {
  qlkh: {},
  qlcp: {},
};

// Helper to initialize permissions
const init = () => {
  const getRoleMap = (config) => {
    const map = {};
    roles.forEach((role) => {
      map[role.key] = config[role.key] || 'R';
    });
    return map;
  };

  const qlkhFieldPermissions = {
    name: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    businessScale: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    taxCode: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    address: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    representativeName: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    representativePosition: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    idNumber: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    phone: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    email: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    contactPerson: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    contactPhone: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    contactEmail: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    businessNeeds: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    potentialLevel: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    priority: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    sourceClassification: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    nsnnSource: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    brandName: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    productsServices: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    ipGroup: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    owner: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    protectionTerritory: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    authorization: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    filingStatus: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    filingDate: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    applicationCode: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    issueDate: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    expiryDate: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    applicationReviewStatus: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    processingDeadline: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    renewalCycle: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    renewalDate: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    reminderDate: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    reminderStatus: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    consultingStatus: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'N',
      director: 'A',
      ceo: 'A',
    }),
    contractStatus: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'A',
      ceo: 'A',
    }),
    contractNumber: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'W',
      director: 'A',
      ceo: 'A',
    }),
    contractValue: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'W',
      director: 'A',
      ceo: 'A',
    }),
    stateFee: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'W',
      director: 'A',
      ceo: 'A',
    }),
    additionalFee: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'W',
      ip_manager: 'W',
      accountant: 'W',
      director: 'A',
      ceo: 'A',
    }),
    createdBy: getRoleMap({}),
    updatedBy: getRoleMap({}),
    updatedAt: getRoleMap({}),
    documentLink: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'W',
      ip_manager: 'A',
      accountant: 'R',
      director: 'W',
      ceo: 'W',
    }),
  };

  const qlcpFieldPermissions = {
    requester: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    department: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    priority: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    requestDate: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    projectCode: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    content: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    description: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    transactionType: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    voucherType: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    transactionObject: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    note: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'W',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    amountBeforeTax: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    taxRate: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    totalAmount: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'R',
      admin: 'R',
      ip_manager: 'R',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    taxCode: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'N',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    voucherNumber: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    voucherDate: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    attachment: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    paymentMethod: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'N',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    accountNumber: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'N',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    bank: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'N',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    paymentStatus: getRoleMap({
      marketing_sales: 'W',
      ip_executive: 'W',
      admin: 'W',
      ip_manager: 'N',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    managerApproval: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'R',
      admin: 'R',
      ip_manager: 'W',
      accountant: 'R',
      director: 'R',
      ceo: 'R',
    }),
    directorApproval: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'R',
      admin: 'R',
      ip_manager: 'R',
      accountant: 'R',
      director: 'W',
      ceo: 'R',
    }),
    accountantReview: getRoleMap({
      marketing_sales: 'R',
      ip_executive: 'R',
      admin: 'R',
      ip_manager: 'R',
      accountant: 'W',
      director: 'R',
      ceo: 'R',
    }),
    adjustReason: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'N',
      admin: 'N',
      ip_manager: 'W',
      accountant: 'W',
      director: 'W',
      ceo: 'R',
    }),
    rejectionReason: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'N',
      admin: 'N',
      ip_manager: 'W',
      accountant: 'N',
      director: 'W',
      ceo: 'R',
    }),
    riskFlag: getRoleMap({
      marketing_sales: 'N',
      ip_executive: 'N',
      admin: 'N',
      ip_manager: 'R',
      accountant: 'R',
      director: 'W',
      ceo: 'W',
    }),
  };

  const schedulingFieldPermissions = {
    seedData: getRoleMap({
      admin: 'W',
      director: 'W',
      ceo: 'W',
      ip_manager: 'W',
      ip_executive: 'R',
      marketing_sales: 'N',
      accountant: 'N',
    }),
    generate: getRoleMap({
      admin: 'W',
      director: 'W',
      ceo: 'W',
      ip_manager: 'W',
      ip_executive: 'R',
      marketing_sales: 'N',
      accountant: 'N',
    }),
    export: getRoleMap({
      admin: 'W',
      director: 'W',
      ceo: 'W',
      ip_manager: 'W',
      ip_executive: 'W',
      marketing_sales: 'N',
      accountant: 'N',
    }),
    config: getRoleMap({
      admin: 'W',
      director: 'W',
      ceo: 'W',
      ip_manager: 'W',
      ip_executive: 'R',
      marketing_sales: 'N',
      accountant: 'N',
    }),
    view: getRoleMap({
      admin: 'R',
      director: 'R',
      ceo: 'R',
      ip_manager: 'R',
      ip_executive: 'R',
      marketing_sales: 'N',
      accountant: 'N',
    }),
  };

  qlkhFields.forEach((group) => {
    group.children.forEach((field) => {
      const fieldConfig = qlkhFieldPermissions[field.key] || getRoleMap({});
      if (!initialPermissions.qlkh[field.key]) initialPermissions.qlkh[field.key] = {};
      roles.forEach((role) => {
        initialPermissions.qlkh[field.key][role.key] = fieldConfig[role.key];
      });
    });
  });

  qlcpFields.forEach((group) => {
    group.children.forEach((field) => {
      const fieldConfig = qlcpFieldPermissions[field.key] || getRoleMap({});
      if (!initialPermissions.qlcp[field.key]) initialPermissions.qlcp[field.key] = {};
      roles.forEach((role) => {
        initialPermissions.qlcp[field.key][role.key] = fieldConfig[role.key];
      });
    });
  });

  schedulingFields.forEach((group) => {
    group.children.forEach((field) => {
      const fieldConfig = schedulingFieldPermissions[field.key] || getRoleMap({});
      if (!initialPermissions.scheduling[field.key]) initialPermissions.scheduling[field.key] = {};
      roles.forEach((role) => {
        initialPermissions.scheduling[field.key][role.key] = fieldConfig[role.key];
      });
    });
  });
};

init();
