// Mock data cho Quản lý công việc nội bộ
export const tasksData = [
  {
    id: 1,
    title: 'Phát triển tính năng quản lý khách hàng',
    description: 'Xây dựng module quản lý khách hàng với đầy đủ tính năng CRUD',
    assignee: 'Nguyễn Văn A',
    assigneeId: 1,
    priority: 'high',
    status: 'in_progress',
    category: 'Development',
    dueDate: '2024-02-15',
    startDate: '2024-01-10',
    progress: 65,
    tags: ['Frontend', 'React'],
    estimatedHours: 40,
    actualHours: 26,
  },
  {
    id: 2,
    title: 'Thiết kế giao diện dashboard',
    description: 'Thiết kế giao diện dashboard cho hệ thống quản lý',
    assignee: 'Trần Thị B',
    assigneeId: 2,
    priority: 'medium',
    status: 'completed',
    category: 'Design',
    dueDate: '2024-01-20',
    startDate: '2024-01-05',
    progress: 100,
    tags: ['UI/UX', 'Design'],
    estimatedHours: 24,
    actualHours: 22,
  },
  {
    id: 3,
    title: 'Kiểm thử hệ thống',
    description: 'Thực hiện kiểm thử toàn bộ hệ thống trước khi release',
    assignee: 'Lê Văn C',
    assigneeId: 3,
    priority: 'high',
    status: 'pending',
    category: 'Testing',
    dueDate: '2024-02-28',
    startDate: '2024-02-20',
    progress: 0,
    tags: ['QA', 'Testing'],
    estimatedHours: 32,
    actualHours: 0,
  },
  {
    id: 4,
    title: 'Viết tài liệu API',
    description: 'Viết tài liệu chi tiết cho các API endpoints',
    assignee: 'Phạm Thị D',
    assigneeId: 4,
    priority: 'low',
    status: 'in_progress',
    category: 'Documentation',
    dueDate: '2024-02-10',
    startDate: '2024-01-25',
    progress: 40,
    tags: ['Documentation', 'API'],
    estimatedHours: 16,
    actualHours: 6.4,
  },
  {
    id: 5,
    title: 'Tối ưu hiệu suất database',
    description: 'Phân tích và tối ưu các query database để cải thiện hiệu suất',
    assignee: 'Hoàng Văn E',
    assigneeId: 5,
    priority: 'medium',
    status: 'in_progress',
    category: 'Backend',
    dueDate: '2024-02-25',
    startDate: '2024-02-01',
    progress: 30,
    tags: ['Database', 'Optimization'],
    estimatedHours: 20,
    actualHours: 6,
  },
  {
    id: 6,
    title: 'Họp với khách hàng',
    description: 'Họp với khách hàng để báo cáo tiến độ dự án',
    assignee: 'Vũ Thị F',
    assigneeId: 6,
    priority: 'high',
    status: 'completed',
    category: 'Meeting',
    dueDate: '2024-01-30',
    startDate: '2024-01-30',
    progress: 100,
    tags: ['Meeting', 'Client'],
    estimatedHours: 2,
    actualHours: 2,
  },
  {
    id: 7,
    title: 'Code review',
    description: 'Review code cho các tính năng mới',
    assignee: 'Đỗ Văn G',
    assigneeId: 7,
    priority: 'medium',
    status: 'pending',
    category: 'Review',
    dueDate: '2024-02-12',
    startDate: '2024-02-08',
    progress: 0,
    tags: ['Code Review'],
    estimatedHours: 8,
    actualHours: 0,
  },
  {
    id: 8,
    title: 'Cập nhật bảo mật',
    description: 'Cập nhật các thư viện và patch bảo mật',
    assignee: 'Bùi Thị H',
    assigneeId: 8,
    priority: 'high',
    status: 'in_progress',
    category: 'Security',
    dueDate: '2024-02-05',
    startDate: '2024-01-28',
    progress: 70,
    tags: ['Security', 'Update'],
    estimatedHours: 12,
    actualHours: 8.4,
  },
  {
    id: 9,
    title: 'Đào tạo nhân viên mới',
    description: 'Đào tạo nhân viên mới về quy trình làm việc',
    assignee: 'Đặng Văn I',
    assigneeId: 9,
    priority: 'low',
    status: 'completed',
    category: 'Training',
    dueDate: '2024-01-25',
    startDate: '2024-01-20',
    progress: 100,
    tags: ['Training'],
    estimatedHours: 16,
    actualHours: 16,
  },
  {
    id: 10,
    title: 'Lập kế hoạch Q1',
    description: 'Lập kế hoạch công việc cho quý 1',
    assignee: 'Ngô Thị K',
    assigneeId: 10,
    priority: 'medium',
    status: 'completed',
    category: 'Planning',
    dueDate: '2024-01-15',
    startDate: '2024-01-10',
    progress: 100,
    tags: ['Planning'],
    estimatedHours: 8,
    actualHours: 8,
  },
];

